### ISSUE TITLE
Client-side issues

### ISSUE THREAD

**Issue by Raven0us** [albertborsos/yii2-gdpr-cookie-consent#14]
1) The extension works properly only under HTTPS, although it should work with HTTP as well (no reason for it not to).

This is due to how the `Secure` flag is used @ `albertborsos\cookieconsent\widgets\CookieWidget::getRemoveCookieJsExpression` and `albertborsos\cookieconsent\actions\CookieSettingsAction::registerAssets`. `Secure` is just a flag, it doesn't expect any value, although it seems to be accepted and parsed by the browser even with a value, but its effect is applied regardless of the value that follows it.

```php
private function getRemoveCookieJsExpression()
{
    return new \yii\web\JsExpression('function(){
        var cookieNames = ' . \yii\helpers\Json::encode($this->getComponent()->getCategories()) . ";
        $.each(cookieNames, function(){
            document.cookie = 'cookieconsent_option_' + this + '=; Domain=" . $this->getComponent()->cookieDomain . '; Path=' . $this->getComponent()->cookiePath . '; Secure=' . $this->getComponent()->cookieSecure . "; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
        });
        var currentUrl = window.location.href;
        var policyUrl = '" . Url::to($this->policyLink, true) . "';
        if (currentUrl==policyUrl) {
            // update cookie settings page if cookieconsent status changed on this page
            window.location.reload();
        }
    }");
}
```

Could become something like this
```php
private function getRemoveCookieJsExpression()
{
    $secureFlag = $this->getComponent()->cookieSecure ? "; Secure " : '';
    return new \yii\web\JsExpression('function(){
        var cookieNames = ' . \yii\helpers\Json::encode($this->getComponent()->getCategories()) . ";
        $.each(cookieNames, function(){
            document.cookie = 'cookieconsent_option_' + this + '=; Domain=" . $this->getComponent()->cookieDomain . '; Path=' . $this->getComponent()->cookiePath . $secureFlag . "; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
        });
        var currentUrl = window.location.href;
        var policyUrl = '" . Url::to($this->policyLink, true) . "';
        if (currentUrl==policyUrl) {
            // update cookie settings page if cookieconsent status changed on this page
            window.location.reload();
        }
    }");
}
```

2) If `cookieHttpOnly` is set to `true`, cookies set via the form aren't eligible to reset (adding a new cookie with the very same name with no value or different value) via client-side cookie handling. Any cookie set via response header `Set-Cookie` with the `httpOnly` flag can no longer be altered via JavaScript. A solution would be to get rid of `cookieHttpOnly` altogether or to bind events that perform AJAX calls to the server on Cookie Consent dismiss/deny/allow.

3) Another annoying issue is the toolbar that keeps sticking around once you personalized your decision. I managed to reproduce it at https://borsosalbert.hu/ as well, just click **Personalize** instead of **Deny**/**Allow** and turn **Ads** or something on, then move around the site, that toolbar won't go away unless you click **Deny** or **Allow**.

**Comment by albertborsos** [comment]
Thanks for your work! I will look after it soon.

**Comment by albertborsos** [comment]
I have just refactored the cookie handling based on your feedback in PR #15 

1. Now I use everything as a flag if it has a boolean value.
2. Yes, `cookieHttpOnly` is unnecessary, I have marked this as deprecated.
3. Now the bar is hidden if you submitted the cookie settings form.

Thanks for your help!
