### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Dezyderyjczyk** [albertborsos/yii2-gdpr-cookie-consent#16]
Hi.

I have copied subdirectory 'messages/en' to 'messakes/pl-PL', translated the entries and nothing. I still have messages in English.

Replacing files doesn't help either.

**Comment by albertborsos** [comment]
Hi!
Sorry for the late response, I hope you already solved it.

I think you had configuration issues, maybe the guide helps:
https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n
