### ISSUE TITLE
You can add the Catan translation.

### ISSUE THREAD

**Issue by lluisclava** [albertborsos/yii2-gdpr-cookie-consent#17]
I Attach the three files needed for the translations to Catalan lenguage.
You can add it to the plugin files if you want.

Form.php:
`<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'flash.message.success' => 'La configuració de la galeta s\'ha actualizat amb exit!',
    'hint.ads' => 'Galetes de remarketing, com la galeta de remarketing de Google AdWords.',
    'hint.behavior' => 'Galetes per guardar comportaments reslacionats amb l\'usuari. M\'agrada aquesta configuració en aquesta forma.',
    'hint.social' => 'Galetes que utilizen els widgets de las xarxes sociales como el complement de la pàgina de Facebook o Google Maps.',
    'hint.statistics' => 'Galetes que ens ajuden a medir el rendimient del lloc web. Per exemple, el seguimient de las accions a Google Analytics y Facebook.',
    'hint.session' => 'Les galetes de sessió són necessàries per distingir a els usuaris en el lloc web.',
    'hint.usage_helper' => 'Galetes per guardar informació com la casella "Recorda\'m" en els formularis de inici de sessió.',
    'input.allowed' => 'On',
    'input.disallowed' => 'Off',
    'label.ads' => 'Galetes de publicitat',
    'label.behavior' => 'Galetes de comportament',
    'label.statistics' => 'Galetes de estadística',
    'label.session' => 'Galetes de sessió',
    'label.social' => 'Galetes de xarxes socials',
    'label.usage_helper' => 'Galetes d\'ajuda d\'ús',
];
`

Policy
`<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Privacy Policy' => 'Política de privacitat',
    'Available documents' => 'Documents disponibles',
    'description' => 'Per obtenir més informació sobre les dades que mantenim, contactans a través de la següent direcció de correo electrònic: <a href="mailto:{email}">{email}</a>.',
];
`

Widget
`<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save' => 'Guardar',
    'allow' => 'Permetre galetes',
    'deny' => 'Rebutjar',
    'dismiss' => 'Descartar',
    'form.error.session-is-required' => '¡La categoria de sessió es obligatòria!',
    'form.error.usage_helper-is-required' => 'Es necessita la categoria d\'ajuda de ús per emmagatzemar aquestes configuracions.',
    'link' => 'Enllaç',
    'message' => 'Ei, sàpigues que en aquest lloc web utilitzem galetes! Si continues utilitzant aquest lloc, assumirem que hi estàs d\'acord. Més info a:',
];
`

**Comment by albertborsos** [comment]
Hi!
Thanks for your work!
I am pretty busy right now, but if you make a PR, I will merge and release it ASAP.
Thanks

**Comment by albertborsos** [comment]
resolved by #18 

You can update the package with composer.
