### ISSUE TITLE
forgot settings

### ISSUE THREAD

**Issue by gomonkey** [albertborsos/yii2-gdpr-cookie-consent#2]
Is not work properly, after setting cookies if I am close the browser and then I re-open the page, the cookies consent, in setting page are reset.

**Comment by albertborsos** [comment]
Please try it on my site: https://borsosalbert.hu/
It works for me after close and reopen the browser.

Please consider that, if you click on the cookie tab on the bottom left, it resets the cookieconsent settings.

**Comment by albertborsos** [comment]
Oh, i see. You are right.

I look after it.

**Comment by gomonkey** [comment]
I see why, the expired cookies date is in the year: 1969

**Comment by gomonkey** [comment]
I fixed like that:
inside src/domains/CookieSettingsDomain.php I change:
`setcookie ( $name, $newValue );`
in:
`setcookie ( $name, $newValue, time() * 86400*356 );` 

now are setting for one year, but I am not really sure if is correct for the GDPR law.

it is possible, maybe, every cookie need different life

**Comment by albertborsos** [comment]
Thanks. I am working on the new release now :)

**Comment by albertborsos** [comment]
Thanks for your work! Now the fixed version is available in release `0.1.0-beta3`.
